domains:
  gl:
    default: [greenlight-monitor]
    projects:
      prod: [sprintliveaction]
  krona:
    default: [partner-krona-feed]
    projects:
      uat: [partner-krona-deploy]
      prod: [partner-krona-deploy]
  operations:
    channels:
      - bot-testing
