domains:
  gl:
    default:
      - bot-testing
      - greenlight-monitor
    projects:
      prod:
        - bot-testing
        - sprintliveaction
  krona:
    default:
      - bot-testing
      - partner-krona-feed
    projects:
      uat:
        - bot-testing
        - partner-krona-deploy
      prod:
        - bot-testing
        - partner-krona-deploy
  operations:
    default:
      - bot-testing
