domain:
  gl:
    channels:
#      - greenlight-monitor
      - bot-testing
    prod:
      channels:
#        - sprintliveaction
        - bot-testing
  krona:
    channels:
#      - partner-krona-feed
      - bot-testing
    prod:
      channels:
#        - partner-krona-deploy
        - bot-testing
  operations:
    channels:
      - bot-testing
