project: stage
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: gl-stage-e1
    namespace: stage
    region: e1
  - cluster: gl-stage-e2
    namespace: stage
    region: e2
syncPolicy:
  automated:
    prune: true
common:
  values:
    ambassador:
      instanceId: stage
    resources:
      limits:
        cpu: 1000m
        memory: 768Mi
      requests:
        cpu: 1000m
        memory: 768Mi
applications:
  - name: galileo-proxy
    version: ">= 0.0.0-0"
