project: stage
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: gl-stage-e1
    namespace: stage
    region: e1
  - cluster: gl-stage-e2
    namespace: stage
    region: e2
syncPolicy:
  automated:
    prune: true
common:
  values:
    resources:
      limits:
        cpu: 1000m
        memory: 768Mi
      requests:
        cpu: 1000m
        memory: 768Mi
    env:
      open:
        LOGGING_LEVEL_ME_GREENLIGHT: DEBUG
        DD_ENV: staging
applications:
  - name: galileo-proxy
    version: ">= 0.0.0-0"
    values:
      loggingAgent: Datadog
      env:
        open:
          REST_TEMPLATE_POOL_MAX_TOTAL: 1000
          REST_TEMPLATE_POOL_MAX_PER_ROUTE: 100
          AUTH_AUTHORIZATION_STABLE_ENDPOINT: http://card-webhooks-internal-service.stage.svc.cluster.local/auth/Authorization
          AUTH_AUTHORIZATION_STABLE_HANDLER: RestRequestHandler
          AUTH_AUTHORIZATION_CANDIDATE_ENDPOINT: ""
          AUTH_AUTHORIZATION_CANDIDATE_HANDLER: ""
          ALERT_ACCOUNT_EVENT_STABLE_ENDPOINT: http://card-webhooks-internal-service.stage.svc.cluster.local/alert/AccountEvent
          ALERT_ACCOUNT_EVENT_STABLE_HANDLER: RestRequestHandler
          ALERT_ACCOUNT_EVENT_CANDIDATE_ENDPOINT: ""
          ALERT_ACCOUNT_EVENT_CANDIDATE_HANDLER: ""
          ALERT_SETTLEMENT_STABLE_ENDPOINT: http://card-webhooks-internal-service.stage.svc.cluster.local/alert/Settlement
          ALERT_SETTLEMENT_STABLE_HANDLER: RestRequestHandler
          ALERT_SETTLEMENT_CANDIDATE_ENDPOINT: ""
          ALERT_SETTLEMENT_CANDIDATE_HANDLER: ""
          ALERT_TRANSACTION_STABLE_ENDPOINT: http://card-webhooks-internal-service.stage.svc.cluster.local/alert/Transaction
          ALERT_TRANSACTION_STABLE_HANDLER: RestRequestHandler
          ALERT_TRANSACTION_CANDIDATE_ENDPOINT: ""
          ALERT_TRANSACTION_CANDIDATE_HANDLER: ""
          DOWNSTREAM_HEALTH_STABLE_ENDPOINT: http://card-webhooks-internal-service.stage.svc.cluster.local/health
          DOWNSTREAM_HEALTH_EVENT_STABLE_HANDLER: RestRequestHandler
