project: prod
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: krona-prod-e1
    namespace: prod
    region: e1
  # - cluster: krona-prod-e2
  #   namespace: prod
  #   region: e2
common:
  values:
    ambassador:
      instanceId: prod
    # Disables all cron jobs in us-east-2. 
    # To enable them, change this to "e1" which will remove them in e2
    e2:
      jobs: {}
gradualRollout: true
applications:
  - name: account-history
    version: 2.11.0
    values:
      hpa:
        minReplicas: 10
        maxReplicas: 12
      env:
        open:
          SPRING_PROFILES_ACTIVE: dbMode
          SPRING_HIKARI_POOL_SIZE: "10"
          SPRING_HIKARI_MAXIMUM_POOL_SIZE: "50"
          SPRING_HIKARI_MINIMUM_IDLE: "10"
          SPRING_HIKARI_CONNECTION_TIMEOUT: "5000"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          REPLICATION_SYNC_USE_SQS: "false"
  - name: account-management
    version: 1.15.0
    values:
      hpa:
        minReplicas: 6
        maxReplicas: 6
      env:
        open:
          SPRING_HIKARI_MAXIMUM_POOL_SIZE: "50"
          SPRING_HIKARI_MINIMUM_IDLE: "10"
          SPRING_HIKARI_CONNECTION_TIMEOUT: "5000"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          ALLOWANCE_GRPC_HOST: ambassador
          ALLOWANCE_GRPC_PORT: "80"
          EXTAUTH_GRPC_HOST: ambassador
          EXTAUTH_GRPC_PORT: "80"
          CHORES_GRPC_HOST: ambassador
          CHORES_GRPC_PORT: "80"
  - name: allowance
    version: 2.6.0
    values:
      hpa:
        minReplicas: 4
        maxReplicas: 6
      env:
        open:
          MOVE_FUNDS_GRPC_HOST: ambassador
          MOVE_FUNDS_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
  - name: authentication
    version: 2.6.0
    values:
      hpa:
        minReplicas: 3
        maxReplicas: 6
      env:
        open:
          AUTHENTICATION_USER_POOLS_PRIMARY_POOL_ID: krona-prod
          AUTHENTICATION_USER_POOLS_PRIMARY_REGION: us-east-1
          AUTHENTICATION_USER_POOLS_SECONDARY_ENABLED: "true"
          AUTHENTICATION_USER_POOLS_SECONDARY_POOL_ID: krona-prod
          AUTHENTICATION_USER_POOLS_SECONDARY_REGION: us-east-2
  - name: charge
    version: 2.10.0
    values:
      hpa:
        minReplicas: 6
        maxReplicas: 10
      env:
        open:
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          STORE_MATCH_GRPC_HOST: ambassador
          STORE_MATCH_GRPC_PORT: "80"
  - name: chores
    version: 1.11.0
    values:
      # temp for matching production schedule
      jobs:
        - name: job-reminder
          schedule: "0 13 * * *"
          concurrency: Forbid
          successHistory: 2
          failedHistory: 3
          activeDeadlineSeconds: 3600
          command:
            - ./job_reminder
      hpa:
        minReplicas: 6
        maxReplicas: 8
      env:
        open:
          CHORES_AWS_DYNAMODB_CONNECTION_KEEP_ALIVE_DURATION: "60000"
          CHORES_AWS_DYNAMODB_IDLE_CONNECTION_TIMEOUT_DURATION: "90000"
          CHORES_AWS_DYNAMODB_MAX_IDLE_CONNECTIONS: "50"
          CHORES_AWS_DYNAMODB_KEEP_WARM_CONNECTIONS: "20"
          CHORES_AWS_DYNAMODB_KEEP_WARM_PERIOD: "30000"
          CHORES_AWS_SQS_WORKERS: "2"
          MOVE_FUNDS_GRPC_HOST: ambassador
          MOVE_FUNDS_GRPC_PORT: "80"
  - name: cobrand-api
    version: 1.20.1
    values:
      hpa:
        minReplicas: 10
        maxReplicas: 12
  - name: cobrand-healthz
    version: 1.7.0
    values:
      hpa:
        minReplicas: 2
        maxReplicas: 2
      env:
        open:
          ACCOUNT_HISTORY_GRPC_HOST: account-history-service
          ACCOUNT_HISTORY_GRPC_PORT: "50051"
          ACCOUNT_MANAGEMENT_GRPC_HOST: account-management-service
          ACCOUNT_MANAGEMENT_GRPC_PORT: "50051"
          ALLOWANCE_GRPC_HOST: allowance-service
          ALLOWANCE_GRPC_PORT: "50051"
          CHARGE_GRPC_HOST: charge-service
          CHARGE_GRPC_PORT: "50051"
          CHORES_GRPC_HOST: chores-service
          CHORES_GRPC_PORT: "50051"
          EXTAUTH_GRPC_HOST: extauth-service
          EXTAUTH_GRPC_PORT: "50051"
          LEDGER_GRPC_HOST: ledger-service
          LEDGER_GRPC_PORT: "50051"
          MOVE_FUNDS_GRPC_HOST: move-funds-service
          MOVE_FUNDS_GRPC_PORT: "50051"
          OUTBOUND_AUTHENTICATION_GRPC_HOST: outbound-authentication-service
          OUTBOUND_AUTHENTICATION_GRPC_PORT: "50051"
          RECONCILIATION_GRPC_HOST: reconciliation-service
          RECONCILIATION_GRPC_PORT: "50051"
          SPENDING_RULES_GRPC_HOST: spending-rules-service
          SPENDING_RULES_GRPC_PORT: "50051"
          STORE_MATCH_GRPC_HOST: store-match-service
          STORE_MATCH_GRPC_PORT: "50051"
  - name: cobrand-server-mock
    version: 0.21.0
  - name: extauth
    version: 2.7.1
    values:
      hpa:
        minReplicas: 4
        maxReplicas: 6
      env:
        open:
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          EXTAUTH_USER_POOLS_PRIMARY: us-east-1_AxAmPRMVE
          EXTAUTH_USER_POOLS_SECONDARY: us-east-2_K1wWbQuOq
  - name: graphql
    version: 1.46.1
    values:
      hpa:
        minReplicas: 10
        maxReplicas: 12
      env:
        open:
          PROCESSOR: krona
          ACCOUNT_HISTORY_GRPC_HOST: ambassador
          ACCOUNT_HISTORY_GRPC_PORT: "80"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          ALLOWANCE_GRPC_HOST: ambassador
          ALLOWANCE_GRPC_PORT: "80"
          CHORES_GRPC_HOST: ambassador
          CHORES_GRPC_PORT: "80"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          MOVE_FUNDS_GRPC_HOST: ambassador
          MOVE_FUNDS_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          STORE_MATCH_GRPC_HOST: ambassador
          STORE_MATCH_GRPC_PORT: "80"
  - name: ledger
    version: 2.6.1
    values:
      hpa:
        minReplicas: 10
        maxReplicas: 12
      env:
        open:
          CLOUD_AWS_DYNAMODB_TABLE_NAME_PREFIX: prod_
          CLOUD_AWS_DYNAMODB_MAX_CONNECTIONS: "100"
          CLOUD_AWS_DYNAMODB_CONNECTION_TIMEOUT: "300"
          CLOUD_AWS_DYNAMODB_CLIENT_EXECUTION_TIMEOUT: "0"
          CLOUD_AWS_DYNAMODB_REQUEST_TIMEOUT: "0"
          CLOUD_AWS_DYNAMODB_SOCKET_TIMEOUT: "5000"
  - name: move-funds
    version: 2.8.2
    values:
      hpa:
        minReplicas: 10
        maxReplicas: 12
      env:
        open:
          CLOUD_AWS_DYNAMODB_TABLE_NAME_PREFIX: prod_
          EXTERNAL_FUNDING_KRONA_RFP_URL: https://api2-ext.jpmchase.net/deposit-account/payments/wires-transfers/first-banking/request-for-payment/v1/payment-requests
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          OUTBOUND_AUTHENTICATION_GRPC_HOST: ambassador
          OUTBOUND_AUTHENTICATION_GRPC_PORT: "80"
          SPENDING_RULE_GRPC_HOST: ambassador
          SPENDING_RULE_GRPC_PORT: "80"
  - name: notification
    version: 2.10.0
    values:
      hpa:
        minReplicas: 3
        maxReplicas: 6
      env:
        open:
          NOTIFICATION_COBRAND_SERVER_MOCK_REST_KRONA_URL: http://cobrand-server-mock-service/notification/krona
          NOTIFICATION_REST_KRONA_URL: https://api2-ext.jpmchase.net/consumer-banking/servicing/alerts-notifications/v1/events
          NOTIFICATION_REST_KRONA_MAX_RETRY: "5"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          OUTBOUND_AUTHENTICATION_GRPC_HOST: ambassador
          OUTBOUND_AUTHENTICATION_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
  - name: outbound-authentication
    version: 1.8.0
    values:
      hpa:
        minReplicas: 3
        maxReplicas: 3
      env:
        open:
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_JWT_AUDIENCE: https://ida.jpmorganchase.com/adfs/oauth2/token
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_JWT_ISSUER: CC-106059-R672683-38163-PROD
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_JWT_SUBJECT: CC-106059-R672683-38163-PROD
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_MAX_RETRY: "5"
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_DATA_CLIENT_ID: CC-106059-R672683-38163-PROD
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_DATA_RESOURCE_EVENT: JPMC:URI:RS-103326-34062-VaderExternal-PROD
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_DATA_RESOURCE_RFP: JPMC:URI:RS-84657-36767-DigitalGrammerRFPSvc-PROD
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_URL: https://ida.jpmorganchase.com/adfs/oauth2/token
          OUTBOUND_AUTHENTICATION_OAUTH_KRONA_MAX_RETRY: "5"
          OUTBOUND_AUTHENTICATION_OAUTH_KRONA_REST_URL: https://api2-ext-oauth.jpmchase.net/oauth/client-credentials/v1/token
  - name: reconciliation
    version: 2.5.0
    values:
      hpa:
        minReplicas: 12
        maxReplicas: 20
      env:
        open:
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_NAME: krona-prod-reconciliation
          CLOUD_AWS_SQS_QUEUES_RECONCILIATION_OVERAGE: prod-reconciliation-overage
          CAMEL_CONFIG_AGGREGATE_TIMEOUT: "450000"
          CAMEL_CONFIG_CONCURRENT_THREADS: "20"
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_AE_FOLDER: ReadyForProcessing/authexpire
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_CDF_FOLDER: ReadyForProcessing/ChaseRejectReport
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_LADF_FOLDER: ReadyForProcessing/LedgerAdjustmentReport
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_PT_FOLDER: ReadyForProcessing/postedtransactions
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_OUTGOING_FOLDER: ReconCache
          CLOUD_AWS_S3_REGION: us-east-2
          CLOUD_AWS_SQS_POLL_SIZE: "10"
          RECONCILIATION_QUEUE_DELAY: "5"
          SPRING_REDIS_ACCOUNT_AGGREGATE_TIMEOUT: "2000"
          SPRING_REDIS_DELAY_INTERVAL: "2000"
          SPRING_REDIS_MAX_DELAY: "30000"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          ACCOUNT_HISTORY_GRPC_HOST: ambassador
          ACCOUNT_HISTORY_GRPC_PORT: "80"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
        awsConfigRef:
          CLOUD_AWS_SQS_QUEUES_CHARGE: charge-fifo-sqs-queue-name
  - name: spending-rules
    version: 2.5.0
    values:
      hpa:
        minReplicas: 7
        maxReplicas: 15
      env:
        open:
          SPRING_HIKARI_POOL_SIZE: "10"
          SPRING_HIKARI_MAXIMUM_POOL_SIZE: "50"
          SPRING_HIKARI_MINIMUM_IDLE: "10"
          SPRING_HIKARI_CONNECTION_TIMEOUT: "5000"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
  - name: store-match
    version: 2.7.0
    values:
      hpa:
        minReplicas: 6
        maxReplicas: 8
      env:
        open:
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          STORE_MATCH_REDIS_POOL_ENABLED: "false"
