project: devinternal
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: krona-internal-e1
    namespace: devinternal
    region: e1
  - cluster: krona-internal-e2
    namespace: devinternal
    region: e2
syncPolicy:
  automated:
    prune: true
common:
  values:
    ambassador:
      instanceId: devinternal
    env:
      open:
        LOGGING_LEVEL_ME_GREENLIGHT: DEBUG
        LOG_LEVEL: debug
    e1:
      hooks:
        postmanTest:
          enable: true
          collections:
            - name: smoke
              env:
                open:
                  COLLECTION_ID: 6747130-d3142053-ba8e-4886-a24f-2374641f7db1
                  ENVIRONMENT_ID: 10066548-8c857ebb-c7cb-4df4-8009-014b4cf57125
                  DELAY_REQUEST: 2000
            - name: charge-general
              env:
                open:
                  COLLECTION_ID: 8154965-2ca50f6e-3e5a-4d54-8912-40ed2ef1fdd6
                  ENVIRONMENT_ID: 10066548-8c857ebb-c7cb-4df4-8009-014b4cf57125
                  DELAY_REQUEST: 10000
    e2:
      jobs: {}
applications:
  - name: account-history
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          SPRING_PROFILES_ACTIVE: dbMode
          SPRING_HIKARI_POOL_SIZE: "10"
          SPRING_HIKARI_MAXIMUM_POOL_SIZE: "50"
          SPRING_HIKARI_MINIMUM_IDLE: "10"
          SPRING_HIKARI_CONNECTION_TIMEOUT: "5000"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          REPLICATION_SYNC_USE_SQS: "false"
  - name: account-management
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          SPRING_HIKARI_MAXIMUM_POOL_SIZE: "50"
          SPRING_HIKARI_MINIMUM_IDLE: "10"
          SPRING_HIKARI_CONNECTION_TIMEOUT: "5000"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          ALLOWANCE_GRPC_HOST: ambassador
          ALLOWANCE_GRPC_PORT: "80"
          EXTAUTH_GRPC_HOST: ambassador
          EXTAUTH_GRPC_PORT: "80"
          CHORES_GRPC_HOST: ambassador
          CHORES_GRPC_PORT: "80"
  - name: allowance
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          MOVE_FUNDS_GRPC_HOST: ambassador
          MOVE_FUNDS_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
  - name: authentication
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          AUTHENTICATION_USER_POOLS_PRIMARY_POOL_ID: krona-devinternal
          AUTHENTICATION_USER_POOLS_PRIMARY_REGION: us-east-1
          AUTHENTICATION_USER_POOLS_SECONDARY_ENABLED: "true"
          AUTHENTICATION_USER_POOLS_SECONDARY_POOL_ID: krona-devinternal
          AUTHENTICATION_USER_POOLS_SECONDARY_REGION: us-east-2
  - name: charge
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          STORE_MATCH_GRPC_HOST: ambassador
          STORE_MATCH_GRPC_PORT: "80"
  - name: chores
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          CHORES_AWS_SQS_WORKERS: "2"
          CHORES_AWS_DYNAMODB_MAX_IDLE_CONNECTIONS: "50"
          CHORES_AWS_DYNAMODB_IDLE_CONNECTION_TIMEOUT_DURATION: "90000"
          CHORES_AWS_DYNAMODB_CONNECTION_KEEP_ALIVE_DURATION: "60000"
          CHORES_AWS_DYNAMODB_KEEP_WARM_PERIOD: "30000"
          CHORES_AWS_DYNAMODB_KEEP_WARM_CONNECTIONS: "20"
          MOVE_FUNDS_GRPC_HOST: ambassador
          MOVE_FUNDS_GRPC_PORT: "80"
  - name: cobrand-api
    version: ">= 0.0.0-0"
  - name: cobrand-healthz
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          ACCOUNT_HISTORY_GRPC_HOST: account-history-service
          ACCOUNT_HISTORY_GRPC_PORT: "50051"
          ACCOUNT_MANAGEMENT_GRPC_HOST: account-management-service
          ACCOUNT_MANAGEMENT_GRPC_PORT: "50051"
          ALLOWANCE_GRPC_HOST: allowance-service
          ALLOWANCE_GRPC_PORT: "50051"
          CHARGE_GRPC_HOST: charge-service
          CHARGE_GRPC_PORT: "50051"
          CHORES_GRPC_HOST: chores-service
          CHORES_GRPC_PORT: "50051"
          EXTAUTH_GRPC_HOST: extauth-service
          EXTAUTH_GRPC_PORT: "50051"
          LEDGER_GRPC_HOST: ledger-service
          LEDGER_GRPC_PORT: "50051"
          MOVE_FUNDS_GRPC_HOST: move-funds-service
          MOVE_FUNDS_GRPC_PORT: "50051"
          OUTBOUND_AUTHENTICATION_GRPC_HOST: outbound-authentication-service
          OUTBOUND_AUTHENTICATION_GRPC_PORT: "50051"
          RECONCILIATION_GRPC_HOST: reconciliation-service
          RECONCILIATION_GRPC_PORT: "50051"
          SPENDING_RULES_GRPC_HOST: spending-rules-service
          SPENDING_RULES_GRPC_PORT: "50051"
          STORE_MATCH_GRPC_HOST: store-match-service
          STORE_MATCH_GRPC_PORT: "50051"
  - name: cobrand-server-mock
    version: ">= 0.0.0-0"
  - name: extauth
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          EXTAUTH_USER_POOLS_PRIMARY: us-east-1_0KL1C4WWY
          EXTAUTH_USER_POOLS_SECONDARY: us-east-2_74gEipP9T
  - name: graphql
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          PROCESSOR: krona
          ACCOUNT_HISTORY_GRPC_HOST: ambassador
          ACCOUNT_HISTORY_GRPC_PORT: "80"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          ALLOWANCE_GRPC_HOST: ambassador
          ALLOWANCE_GRPC_PORT: "80"
          CHORES_GRPC_HOST: ambassador
          CHORES_GRPC_PORT: "80"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          MOVE_FUNDS_GRPC_HOST: ambassador
          MOVE_FUNDS_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          STORE_MATCH_GRPC_HOST: ambassador
          STORE_MATCH_GRPC_PORT: "80"
  - name: ledger
    version: ">= 0.0.0-0"
    values:
      e1:
        hooks:
          acceptanceTest:
            enable: true
            env:
              open:
                LEDGER_GRPC_HOST: ambassador
                LEDGER_GRPC_PORT: 80
      env:
        open:
          CLOUD_AWS_DYNAMODB_TABLE_NAME_PREFIX: devinternal_
          CLOUD_AWS_DYNAMODB_MAX_CONNECTIONS: "100"
          CLOUD_AWS_DYNAMODB_CONNECTION_TIMEOUT: "300"
          CLOUD_AWS_DYNAMODB_CLIENT_EXECUTION_TIMEOUT: "0"
          CLOUD_AWS_DYNAMODB_REQUEST_TIMEOUT: "0"
          CLOUD_AWS_DYNAMODB_SOCKET_TIMEOUT: "5000"
  - name: move-funds
    version: ">= 0.0.0-0"
    values:
      e1:
        hooks:
          acceptanceTest:
            enable: true
            env:
              open:
                ACCOUNT_MANAGEMENT_GRPC_HOST: "ambassador"
                ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
                EXTERNAL_FUNDS_GRPC_HOST: "ambassador"
                EXTERNAL_FUNDS_GRPC_PORT: "80"
                LEDGER_GRPC_HOST: "ambassador"
                LEDGER_GRPC_PORT: "80"
                MOVE_FUNDS_GRPC_HOST: "ambassador"
                MOVE_FUNDS_GRPC_PORT: "80"
                SPENDING_RULE_GRPC_HOST: "ambassador"
                SPENDING_RULE_GRPC_PORT: "80"
      env:
        open:
          CLOUD_AWS_DYNAMODB_TABLE_NAME_PREFIX: devinternal_
          EXTERNAL_FUNDING_KRONA_RFP_URL: http://cobrand-server-mock-service/rfp/krona
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          OUTBOUND_AUTHENTICATION_GRPC_HOST: ambassador
          OUTBOUND_AUTHENTICATION_GRPC_PORT: "80"
          SPENDING_RULE_GRPC_HOST: ambassador
          SPENDING_RULE_GRPC_PORT: "80"
  - name: notification
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          NOTIFICATION_COBRAND_SERVER_MOCK_REST_KRONA_URL: http://cobrand-server-mock-service/notification/krona
          NOTIFICATION_REST_KRONA_URL: http://cobrand-server-mock-service/notification/krona
          NOTIFICATION_REST_KRONA_MAX_RETRY: "5"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          OUTBOUND_AUTHENTICATION_GRPC_HOST: ambassador
          OUTBOUND_AUTHENTICATION_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
  - name: outbound-authentication
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_JWT_AUDIENCE: jwt-audience
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_JWT_ISSUER: jwt-issuer
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_JWT_SUBJECT: jwt-subject
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_DATA_CLIENT_ID: data-client-id
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_DATA_RESOURCE_EVENT: data-resource-event
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_DATA_RESOURCE_RFP: data-resource-rfp
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_REST_URL: http://cobrand-server-mock-service/outbound-authentication/krona/adfs
          OUTBOUND_AUTHENTICATION_ADFS_KRONA_MAX_RETRY: "5"
          OUTBOUND_AUTHENTICATION_OAUTH_KRONA_REST_URL: http://cobrand-server-mock-service/outbound-authentication/krona/oauth2
          OUTBOUND_AUTHENTICATION_OAUTH_KRONA_MAX_RETRY: "5"
  - name: reconciliation
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_NAME: krona-devinternal-reconciliation
          CLOUD_AWS_SQS_QUEUES_RECONCILIATION_OVERAGE: devinternal-reconciliation-overage
          CAMEL_CONFIG_AGGREGATE_TIMEOUT: "450000"
          CAMEL_CONFIG_CONCURRENT_THREADS: "20"
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_AE_FOLDER: ReadyForProcessing/authexpire
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_CDF_FOLDER: ReadyForProcessing/ChaseRejectReport
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_LADF_FOLDER: ReadyForProcessing/LedgerAdjustmentReport
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_INCOMING_PT_FOLDER: ReadyForProcessing/postedtransactions
          CLOUD_AWS_S3_BUCKETS_RECONCILIATION_OUTGOING_FOLDER: ReconCache
          CLOUD_AWS_S3_REGION: us-east-2
          CLOUD_AWS_SQS_POLL_SIZE: "10"
          RECONCILIATION_QUEUE_DELAY: "5"
          SPRING_REDIS_ACCOUNT_AGGREGATE_TIMEOUT: "2000"
          SPRING_REDIS_DELAY_INTERVAL: "2000"
          SPRING_REDIS_MAX_DELAY: "30000"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          SPENDING_RULES_GRPC_HOST: ambassador
          SPENDING_RULES_GRPC_PORT: "80"
          ACCOUNT_HISTORY_GRPC_HOST: ambassador
          ACCOUNT_HISTORY_GRPC_PORT: "80"
          ACCOUNT_MANAGEMENT_GRPC_HOST: ambassador
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
        awsConfigRef:
          CLOUD_AWS_SQS_QUEUES_CHARGE: charge-fifo-sqs-queue-name
  - name: spending-rules
    version: ">= 0.0.0-0"
    values:
      env:
        open:
          SPRING_HIKARI_POOL_SIZE: "10"
          SPRING_HIKARI_MAXIMUM_POOL_SIZE: "50"
          SPRING_HIKARI_MINIMUM_IDLE: "10"
          SPRING_HIKARI_CONNECTION_TIMEOUT: "5000"
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
  - name: store-match
    version: ">= 0.0.0-0"
    values:
      e1:
        hooks:
          acceptanceTest:
            enable: true
            env:
              open:
                STORE_MATCH_GRPC_HOST: ambassador
                STORE_MATCH_GRPC_PORT: 80
      env:
        open:
          LEDGER_GRPC_HOST: ambassador
          LEDGER_GRPC_PORT: "80"
          STORE_MATCH_REDIS_POOL_ENABLED: "false"
  - name: sealed-secrets
    version: ">= 0.0.0-0"
    values:
      e1:
        sealedSecrets:
          - name: artifactory-secrets
            encryptedData:
              ARTIFACTORY_USERNAME: AgBShQO9e2n6AAuYFi91WJcKcOK0/0qNGjf+7XwgPBvm4/hKvrM4VmUlhHylmFBWK3u4ZKlK9mI/dQasuWRim6M4cnfmsftBfdmE2YaHXAvyFuVb1afoxS5+TSLZE6ZrPG7arv3XdgZN7Z8rsNcgpykS9/kcmvVQ0uMfVC3voLxQbmgu/RLGt5Jjt/lWy7Txvd6eOtcesNxK6KZf9oGQCeSpyxC9wNA7Z5Wxfv1k5Mz3+/9dx48fyW6oB9YSioGUNyjfBUPQz5pyypprAAyx3FM0H9c8ZFBXaXIBqMOZDfVESHvTk59r8Jepuq1yCZgKFG+i2M8yfGyEKFC8BzUVnlIJyH+iIRi9QIK67d920FMzHEcGelCvAtjK93Nfw0BzXb0CT0TfH3bYxv8jZmoRu+Dp+hgvIWsHp5JDUFWFPP0rbOJ0yvr340Uao8AyjJWFK6jvF6L9acM/oVc1mXxf842kwhlV6DLbS8Balo+C4IYRGW7xDzgvxdHAk17gP6bSTZACcHYeF/nsV45axLmPtJFde5ZVbySrH/mZwtke5rmt+VYP2orqaUqk8bBkZ9vHNomdG7AxSs93zvP/HHkSSRJNXG5GaXSBEaJAg8awYOwBGuIkK78HfMNlgwi+3qD8+tyvceF3eKNpT/985Ape5glEhOhnEIo9uJSjL5qhLwRHbsHhXlLq7GMPzyCHYWqs6CU=
              ARTIFACTORY_TOKEN: AgAWGdggJ4hMGX0JFcAH2VhOtBgzZcBIPYKRiECWNpL15dhr8Viy9bKTWE+i6QM3TY3P0XRscnDmARABGDSwlKKkO0P6qqsjP56Qzl9P93qn63pol/yaC19bI7lEcQLC5Mj6+4cXXP6RHUhQ66zuNGkjH4T4pg9z5JKgXagXZD19wVKzEMZ/ifkGeLHbWsbHOsXCz02vWpt5AkOMYhQeV/CfNjsmglxfh2UpWM/F3+iUvbM/mXJGBjLicB/Z4DwZosBxjk2ou+8e9i2XIFD7B1/0fpQZv8z+3KpBrPljLO9XGh2sIbcMBrxx7w90lethGyjGF5SNY3sZyfULn+iK2PCF9W2zsFhCHF9sOeim79Eb/dKxpNxuU4OwPr89JdCe9/88eertaJwqF4xBbRc/pQ5IxTI7HaGGwfaOdQ5tYeYSW2mDkepSxdLQoO+10iQ2yWEju5sWwkfrGxdKymoPRaE7BZ1gPqTXau9w4X2Wate5Neg9RuMU4LCqpihU+CRnv8tTYcoiNKfFLrom0CQ4HVBDqLZO1pfg74XmUtLVlq/PUvH2p6+stGGz2waXZ6EfeKMTEmk4G5K/iRox+5gDLpK7N0y9VyTdA1cg/xFjXyuN6hjI5xJII8AeDdLaK3rQSfZ99VdgHwHA45PsvrqXZ9x5ragXYYeT0oeakU7D4ykY2mMk7zwbdS69tZN79PhNfSU=
          - name: postman-secrets
            encryptedData:
              CLIENT_ID: AgBVwVT+cij9MORExoZdl5tsuotU/yI+6NKGTByE7hqWPpcHNFTMrn962/c3hjo1nE/p8mg9gVHhqv3kVtKuefra3P8h4WUYpFgkqfQEyoAjArsBGq8eYDydexuzLYukZnCt6T4UKEfmCylu2Vi/NCit7NenmqqVldQxDG+9XZ3LE2GkEyz9qmCucJP04SeHuKRD4YhMHesRaiR1k/uEl2DMqw2OZbtesFdfRhoj/bbBSDylw5ODV+1Pp5n+dfNI6iKJY0EbJrPKJLD1Wao5irtOYyaLcspR/ZQGUDc6bpm5d7hlguzubEexh9Ce8WOtSrlgpClgA538AqZdve274x1qUaQr8CD6KD2oxHKcyneNnZHxT4KOVLl+2JCrQWEV0wH/m1iTiy3R4PY6WlgMNGb5+mMiQJ+sIEc/XNxjDAAXcKYvr7g6iDB0ehffp4hjGGCbSBDQqK/yrcLObGg/vZ/e4sKBxKBuN+8Z/6hBFp4mM22jogdzlGC47XeBnWEhDswZFNaCUitaQQMRFnK4omZzI7t658ItqmrtxPYkv2xQyMD8oxUnSe1+qc6Ol+ASeV7RP++VByRNrrxINqMRINkcNJ7bODwB9pofftf5CUGM8Mn8iLiiRtmXv5KAXceQPuAZ0x6uez/9E8fTXYUGT2MqxuVtZgbbvOwBsS1amVaL/wjagfSo0kaJz+OxCYQsJCuRve0f2fCPMvDng+Yq/0A0FKrQQmLDrGducg==
              CLIENT_SECRET: AgCU7YCXZRyMWSyvdI9+Zz6aYld4spmf2XKhUkvkEODzCTTkp3AlAlcMKn6RH79JmjWcV0qCURtYfSfqzdV9odGISv4HA1MZnni9KX+SaIfwmqnHRKk7i30xBWd7ZNY/Z6/ajRIGwmiJQNy2KOczIgzhPR3KSin4nHsPTK5QUJ52UaWYM8ZGGcxAgLEYzijdrtYO+VBi7eSHY5oiEdPoUvg/uYp5SPET1K/POqmCP7bo3whA64dTVK7FAbr/bSGMSpPy+8toP8f3wjsdj4AkVOOHSoJpy5kDuJGb/cjuBdshGojXCO8M2VVPiSR1yb9oifjGUb+4+xRDETHoPsp/k+cAdnRtnMj9vkZzmhH9cg6Q6avlsrcrJFVsuAb5k7urxvJVXVZe48vHR7hL+bbLDAzVtNv0j10ZCQOQplCk0NHKEv02yVDgaURerp3dxQ9y8uv1aYzPCeiQacLuDesiVlW+sU2z1WmW8ZZR6S7EQ7Wu3fy1xB3y2BwwJdJlYmQb5UOJ5BvB224aG7DDfI4XvIVtACaF7aY6dtt+8B34mIbHNq+vWoy81tyVBYK5uAE71M9h2U08G+l1KOXx4cZIUq0vTce14VFiNfLFPj2xbts0bR4zCCGRFXc81oTbnZst/ghv3qtoAqcAK12bHXA2hzm6dbeBVzSTQifmtufkcvgI03Ft+yhJHL56h8jPoFfO8N6XHVlVvh6sjA1TYvFvRTNuvq22buCqxXKRgYkF1pbrrrHBYmBTPtebmRvl8qjwzKd8KEl4
              POSTMAN_TOKEN: AgCy8JiB9rZgpoJQ4LtpxRqRWDUVUA+LjMnjb4LoVBiZFxjcYQhxfmm9wqwyH/J6nxBUGLPVc3H+KNxmcR4drTr83tl/R1siX3xAghf+jfWQErSdIEX2B+ebS0iXHC6jSMv2OVFa8bmeiEPKTzY8KKWUzJA/jZxfwsQr30ch6KerjbZh0lB1gWhXDuRWt1MCBywQJXyRI+EGuFDKq1WJNJ6VG4QJimYL8n/qeBHn175y4c13WRx+BxftrsedLUbpKumwl8im2JhQYEA4vY4taKHFb0nv2oRwNk+22jg1hAJDR+guhBqGqG+Kl87uzT5Sa7C7mz9FKeGCaxCZKhreWs3SRd7NKtdJ8cd++CdfrRtgBBiJ1EQhGfkHZmWrslOhez7aB2JVzjec82iqDva2+c3lvOBeDQ0qph5xVt42Rj9IKxGcUmOYL+0CaZ0N4bzEn53zH5HctZj4kU+nQ+YOj5KDpvqXRHRI+jrJ9XddSE5uJ8cFD84ezh5uN6HawtRMCHaqXaGI0+D6KXR0GpYpXNRBGe6dr4HJeToZ1t9bV3TgaWlimeEweP6fz58JmBhDGUNrEssJB6LXVm2AkzLBvW/gpIykiiSz4/mEude+zISt+6H3qYPdwAsJOl5np8Ra5W7sCjWnNVfzObCg1OarPZD0vuTkeCBj30EfX/z2LhFnGOrpNqKulxoA10vFSOtEzqQhgJsFnm7ZyOSpUTtDCn7OPFzj3PAb0J+xeTIxIcj+k512QRRwYFvVGXvXPJnoYt/dxmuLHYgVIADEJCpRwavt
