{{- range $dest := .Values.destinations }}
{{- range $app := $.Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.lob }}-{{ $app.name }}-{{ $dest.namespace }}-{{ $dest.region }}
  namespace: {{ $.Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    application: {{ $app.name }}
    cluster: {{ $dest.cluster }}
    namespace: {{ $dest.namespace }}
    region: {{ $dest.region }}
spec:
  project: {{ $.Values.lob }}-{{ $.Values.project }}
  source:
    chart: {{ $app.name }}
    helm:
      releaseName: {{ $app.name }}-{{ $dest.namespace }}
      values: |
        {{- toYaml $.Values.common.values | trim | nindent 8 }}
        {{- if hasKey . "values" }}
        {{- $regionValues := (index .values $dest.region) }}
        {{- $noRegionValues := omit $app.values "e1" "e2" }}
        {{- $values := merge $regionValues $noRegionValues }}
          {{- toYaml $values | trim | nindent 8 }}
        {{- end }}
      parameters:
        - name: application
          value: {{ $app.name }}
        - name: cluster
          value: {{ $dest.cluster }}
        - name: namespace
          value: {{ $dest.namespace }}
        - name: region
          value: {{ $dest.region }}
    repoURL: {{ $.Values.source.repo }}
    targetRevision: {{ $app.version | quote }}
  destination:
    name: {{ $dest.cluster }}
    namespace: {{ $dest.namespace }}
  {{- if hasKey $.Values "syncPolicy" }}
  syncPolicy:
    {{- toYaml $.Values.syncPolicy | trim | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
