project: prod
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: gl-prod-e1
    namespace: prod
    region: e1
  - cluster: gl-prod-e2
    namespace: prod
    region: e2
options:
  ignoreStartupProbe: true
annotations:
  notifications.argoproj.io/subscribe.on-deployed.act: ""
applications:
  - name: account-management-dtc
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.294-46fbd54"
    values:
      e1:
        cronjobs:
          cronjob2: # account-management-process-pricing-plan-changes
            suspend: true
  - name: card-webhooks
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "3.8.96-25a8cf8"
  - name: commander
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "2.0.256-55f5ea8"
    values:
      e1:
        env:
          open:
            LOG_GROUP_JOBS: /eks/gl-prod-e1/prod/server-api-jobs-delayed
            LOG_GROUP_WEBHOOKS: /eks/gl-prod-e1/prod/card-webhooks
      e2:
        env:
          open:
            LOG_GROUP_JOBS: /eks/gl-prod-e2/prod/server-api-jobs-delayed
            LOG_GROUP_WEBHOOKS: /eks/gl-prod-e2/prod/card-webhooks
  - name: communication
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.4.0"
  - name: drive-wealth
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.10.0"
    values:
      ambassadorEdgeStack:
        use: "true"
  - name: experimentation-id
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.54-738e722"
  - name: external-funds
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.240-ce92083"
  - name: external-funds-webhooks
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "0.0.42-83afae8"
  - name: feature-toggles
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.33-61fa7cb"
    values:
      ambassador:
        enabled: true
        mapping:
          host: "^(ft|featuretoggle)\\.greenlight\\.me$"
          regex: true
      baseUrl: https://ft.greenlight.me
      datadog:
        enabled: true
        metrics: true
      db:
        name: production_unleash
      dtc_deployment: true
      node_env: production
      replicaCount: "3"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 512Mi
      service:
        port: "80"
  - name: galileo-proxy
    version: 0.10.0
    values:
      loggingAgent: Datadog
      resources:
        limits:
          cpu: 1000m
          memory: 768Mi
        requests:
          cpu: 1000m
          memory: 768Mi
      hpa:
        minReplicas: 6
        maxReplicas: 24
      env:
        open:
          LOGGING_LEVEL_ME_GREENLIGHT: INFO
          DD_ENV: production
          REST_TEMPLATE_POOL_MAX_TOTAL: 1000
          REST_TEMPLATE_POOL_MAX_PER_ROUTE: 200
          AUTH_AUTHORIZATION_STABLE_ENDPOINT: http://card-webhooks-internal-service.prod.svc.cluster.local/auth/Authorization
          AUTH_AUTHORIZATION_STABLE_HANDLER: RestRequestHandler
          AUTH_AUTHORIZATION_CANDIDATE_ENDPOINT: ""
          AUTH_AUTHORIZATION_CANDIDATE_HANDLER: ""
          ALERT_STABLE_ENDPOINT: http://card-webhooks-internal-service.prod.svc.cluster.local/alert/
          ALERT_STABLE_HANDLER: RestRequestHandler
          DOWNSTREAM_HEALTH_STABLE_ENDPOINT: http://card-webhooks-internal-service.prod.svc.cluster.local/health
          DOWNSTREAM_HEALTH_EVENT_STABLE_HANDLER: RestRequestHandler
  - name: gift-of-greenlight
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.116-f37e24b"
  - name: gift-service
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.111-9c87a44"
  - name: giving
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.121-af7f775"
    values:
      ambassadorEdgeStack:
        use: "true"
      e1:
        cronjobs:
          cronjob1: # giving-update-donations
            suspend: true
      e2:
        cronjobs:
          cronjob3: # giving-update-donation-totals
            suspend: false
#   - name: identity-prefill
#     repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
#     version: "1.0.16-dca4210"
  - name: inbound-authentication
    version: 0.8.0-develop.12
    values:
      hpa:
        minReplicas: 10
        maxReplicas: 20
      resources:
        limits:
          cpu: "1000m"
          memory: "1024Mi"
        requests:
          cpu: "1000m"
          memory: "1024Mi"
      loggingAgent: "Datadog"
      env:
        open:
          LOGGING_LEVEL_ME_GREENLIGHT: INFO
          ACCOUNT_MANAGEMENT_GRPC_HOST: "ambassador"
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          INBOUND_AUTHENTICATION_PROFILE: "DTC"
          CACHE_TYPE: "redis"
          CACHE_REDIS_SCHEMA: "3"
          CACHE_REDIS_HOST: "redis-writer"
          CACHE_REDIS_PORT: "6379"
          SPRING_CACHE_REDIS_TIME_TO_LIVE: "60000"
          DD_ENV: "production"
      ambassador:
        instanceId: "default"
        enableFilter: true
  - name: invest-profile
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.23.0"
    values:
      ambassadorEdgeStack:
        use: "true"
  - name: kyc-service
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.190-26d3078"
  - name: optimizely
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.75-dbf8660"
  - name: registration
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.32.0"
    values:
      hpa:
        minReplicas: 4
        maxReplicas: 10
  - name: registration-mapper
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.150-d6ad0cb"
    values:
      hpa:
        minReplicas: 4
        maxReplicas: 10
  - name: savings
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.6.0"
  - name: sealed-secrets
    version: "1.1.0"
    values:
      e1:
        sealedSecrets:
          - name: galileo-proxy-secrets
            encryptedData:
              SENTRY_DSN: AgDFAQB18RXXOMkZepltQFAPJqBbYm2PVwcAaRnak0tMQbDodUCP2UG+FNUo9Y3Zc155mri25u+3YapV3JGCYHPjkFv7YY/3UerhS6feRccXIpJnnwmfaZmx7KR6yN98V/1z8Zf2ra49dHGZgOvo/nm+iH2LTLShYVq/6WMlMof1yhK1ML6kll0oBReBaawzLWIYVoN8aKO2yUDGixJAEnLsl5/ncN/e9YA7uTNfmmxsTXHwOPRTxxh+VBmXCXuv+O0n+rZ68mHujAXibtqfF6UK2bz2BDC954MX5SqD+Fx8Z9kZab34kAjQg8jD0CcALwReFlfZlok3+0N50IPCrKLdrlocESbit7Lgv/SkiN4QodDdZPdXYLo0GTsfsL/E8RP359Zdb0YztosI641+rm9Wiuouhm7Q3YEBYYke+UUMy9Nq9O3M3eaTI7507WSwnqg7+8bQuPqFOW1wZmr2n8iRDYXH05iMTD2hdTQIdTyUt1OJO7PinPEAz3fhVw8wZICRLKBDCq+sDqryXQVvlrOhHv1QN7FMj12YdZwYvQYmWjfUAsafx+wLH+ZLipoUsjEjhgApX6uoROv6UzPpW6XTAGlgQD2wtF34W+gAkWEPselxy5ism/giNKvpH8exQZpkjkeDRtTzlebXhuUSGgRg59iheZ9mmw1WSofqVJgCn1tq/YmX8TnsNXJeU99TsmmQDwNjyLyQklv95ULi0kVjubmWwNzX8Lqx2xSJp74RWkFrQgpKTGg90hrwqGE69Ma35Y4oQZEc+d05F6LOORoY/aovyiGfsgQ=
      e2:
        sealedSecrets:
          - name: galileo-proxy-secrets
            encryptedData:
              SENTRY_DSN: AgBkoODYVMi7YulFi8/Ew45N39fE1Pk6T169e4+jJBfeCgJ49ASHwkA+E3QvM/9MqcATddMzOVt0T+QY+oVzkkupSuMf3Egb75NqsPEJBbgQzFPbEBS8R+6ZWtdFhID5CuvoGCau2QIbpOnXRZoazitDJh33LrJJbCGGkJ/QgpKHea6AqExFWidG3LdNvXosd13sxeQU0N9vk6jF1UdcwdJ45OHHu6LDxFYjBukj/f+HxSZ3UfVhqViYMftuKPR65fFvD6GWPYxxNlHaBIJ7e69kcojBFslPXkIpu6nINnwFzfWIPxuZWTQeSeojc669jKAERRoj3WGuyUQmAxQQ6vzB2KyRQrKX+gToMYV/O1OoEg8zs2RLlRgbjm4sEbihVpKyMFek6wopYCE41vH/Ri1JQrKaQ9vA1Dr+l9KDaMCW/UEqQttFcmtGfaWd9nAHVRXDtWgqPYVzjPgwAPijJv3ETzZHTijQC6LQksuEVlmfTZVuHhj9C/H664TLahSMS9hJ3oKkxglkRpWheYLYMXrqLBTAfliLkPP3rV0AuS+OsKN0Mo/2DeSeKYgBmJ3NV68quA+svR8GXYgawfK8B80ivgSQtfu/eomDv9a3NsWj2/3JdwHlBoKLzAmkjhHmcP2CyAw1qPHhTh36vDts07jwcy1GxOsQ7nXzhMH/bE2JZIF4SlqzRPQzh//Mh6MOPy0m1IVKaz+GtPDxqv7Okt4iqXBlAh7fPhEpnwbkF6GQ/GdfIR8uGWbGxUJYT5inOGslfAqSVNvbgdocj/vzXgTNcpODNQNJOk4=
  - name: server-api
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "3.7.1370-10c19a3"
  - name: stargateway
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.676-05f180e"
  - name: user-action
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.15.0"
  - name: webreg
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-prod
    version: "1.0.931-55002e9"
    values:
      ambassadorEdgeStack:
        use: "true"
