project: qa
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: gl-stage-e1
    namespace: qa
    region: e1
  - cluster: gl-stage-e2
    namespace: qa
    region: e2
syncPolicy:
  automated:
    prune: true
options:
  ignoreStartupProbe: true
applications:
  - name: account-management-dtc
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.294-46fbd54"
    values:
      e1:
        cronjobs:
          cronjob2: # account-management-process-pricing-plan-changes
            suspend: true
  - name: card-webhooks
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "3.8.96-25a8cf8"
  - name: commander
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "2.0.278-fab6cf4"
  - name: communication
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.5.0"
  - name: drive-wealth
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.8.0"
  - name: experimentation-id
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.54-738e722"
  - name: external-funds
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.240-ce92083"
  - name: external-funds-webhooks
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "0.0.42-83afae8"
  - name: gift-of-greenlight
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.116-f37e24b"
  - name: gift-service
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.109-24e594c"
  - name: giving
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.121-af7f775"
    values:
      e1:
        cronjobs:
          cronjob1: # giving-update-donations
            suspend: true
  - name: identity-prefill
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.16-dca4210"
  - name: inbound-authentication
    version: "0.8.0-develop.19"
    values:
      hpa:
        minReplicas: "2"
        maxReplicas: "2"
      resources:
        limits:
          cpu: 1000m
          memory: 768Mi
        requests:
          cpu: 1000m
          memory: 768Mi
      loggingAgent: "Datadog"
      env:
        open:
          ACCOUNT_MANAGEMENT_GRPC_HOST: "qa-ambassador"
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          CACHE_TYPE: "redis"
          CACHE_REDIS_SCHEMA: "3"
          CACHE_REDIS_HOST: "redis-writer"
          CACHE_REDIS_PORT: "6379"
          DD_ENV: "staging"
          INBOUND_AUTHENTICATION_PROFILE: "DTC"
          LOGGING_LEVEL_ME_GREENLIGHT: DEBUG
          SENTRY_ENVIRONMENT: "staging"
          SPRING_CACHE_REDIS_TIME_TO_LIVE: "1800"
      ambassador:
        instanceId: "default"
        enableFilter: true
  - name: invest-profile
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.23.0"
  - name: kyc-service
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.190-26d3078"
  - name: optimizely
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.74-7e53324"
  - name: registration-mapper
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.150-d6ad0cb"
  - name: registration
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.16.0"
  - name: savings
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.6.0"
  - name: server-api
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "3.7.1353-d8c0099"
  - name: stargateway
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.676-05f180e"
  - name: user-action
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.15.0"
  - name: webreg
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: "1.0.916-3efc27c"
