project: qa
source:
  repo: https://greenlight.jfrog.io/artifactory/gl-helm
destinations:
  - cluster: gl-stage-e1
    namespace: qa
    region: e1
  - cluster: gl-stage-e2
    namespace: qa
    region: e2
syncPolicy: {}
options:
  ignoreStartupProbe: true
applications:
  - name: account-management-dtc
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
    values:
      e1:
        cronjobs:
          cronjob2: # account-management-process-pricing-plan-changes
            suspend: true
  - name: card-webhooks
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: commander
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: communication
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: drive-wealth
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: experimentation-id
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: external-funds
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: external-funds-webhooks
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: galileo-proxy
    version: ">= 0.0.0-0"
    values:
      hpa:
          minReplicas: 3
          maxReplicas: 4
      loggingAgent: Datadog
      resources:
        limits:
          cpu: 1000m
          memory: 768Mi
        requests:
          cpu: 1000m
          memory: 768Mi
      env:
        open:
          ALERT_STABLE_ENDPOINT: http://card-webhooks-internal-service.qa.svc.cluster.local/alert/
          ALERT_STABLE_HANDLER: RestRequestHandler
          AUTH_AUTHORIZATION_CANDIDATE_ENDPOINT: ""
          AUTH_AUTHORIZATION_CANDIDATE_HANDLER: ""
          AUTH_AUTHORIZATION_STABLE_ENDPOINT: http://card-webhooks-internal-service.qa.svc.cluster.local/auth/Authorization
          AUTH_AUTHORIZATION_STABLE_HANDLER: RestRequestHandler
          DD_ENV: staging
          DOWNSTREAM_HEALTH_STABLE_ENDPOINT: http://card-webhooks-internal-service.qa.svc.cluster.local/health
          DOWNSTREAM_HEALTH_EVENT_STABLE_HANDLER: RestRequestHandler
          LOGGING_LEVEL_ME_GREENLIGHT: DEBUG
          REST_TEMPLATE_POOL_MAX_PER_ROUTE: 200
          REST_TEMPLATE_POOL_MAX_TOTAL: 1000
  - name: gift-of-greenlight
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: gift-service
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: giving
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
    values:
      e1:
        cronjobs:
          cronjob1: # giving-update-donations
            suspend: true
  - name: identity-prefill
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: inbound-authentication
    version: ">= 0.0.0-0"
    values:
      hpa:
        minReplicas: "2"
        maxReplicas: "2"
      resources:
        limits:
          cpu: 1000m
          memory: 768Mi
        requests:
          cpu: 1000m
          memory: 768Mi
      loggingAgent: "Datadog"
      env:
        open:
          ACCOUNT_MANAGEMENT_GRPC_HOST: "qa-ambassador"
          ACCOUNT_MANAGEMENT_GRPC_PORT: "80"
          CACHE_TYPE: "redis"
          CACHE_REDIS_SCHEMA: "3"
          CACHE_REDIS_HOST: "redis-writer"
          CACHE_REDIS_PORT: "6379"
          DD_ENV: "staging"
          INBOUND_AUTHENTICATION_PROFILE: "DTC"
          LOGGING_LEVEL_ME_GREENLIGHT: DEBUG
          SENTRY_ENVIRONMENT: "staging"
          SPRING_CACHE_REDIS_TIME_TO_LIVE: "1800"
      ambassador:
        instanceId: "default"
        enableFilter: true
  - name: invest-profile
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: kyc-service
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: optimizely
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: registration
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: registration-mapper
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: savings
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: server-api
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: stargateway
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: testaway
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: user-action
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
  - name: webreg
    repo: https://greenlight.jfrog.io/artifactory/gl-helm-qa
    version: ">= 0.0.0-0"
