name: Helm Lint
on:
  pull_request:
    branches:
      - main
jobs:
  helm-lint:
    name: Lint Helm files
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Lint Helm files
        run: |
          domains=(appofapp gl krona operations)
          for domain in "${domains[@]}"; do
              if ls $domain/values-*.yaml > /dev/null 2>&1; then
                for env in $domain/values-*.yaml; do
                    helm lint $domain --values $env
                done
              else
                  helm lint $domain
              fi
          done
