name: Pull Request Labeler
on:
  - pull_request_target
jobs:
  labeler:
    name: Pull Request Labeler
    runs-on: self-hosted
    steps:
      - name: Run Pull Request Labeler
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
