name: Pull Request Linter
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  lint-pr:
    name: Lint pull request
    runs-on: self-hosted
    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          path: .github/actions
          ref: v4
          repository: GreenlightMe/actions
          token: ${{ secrets.GREENLIGHTBOT_PAT }}
      - name: Lint pull request title
        uses: ./.github/actions/lint/pull-request
        with:
          token: ${{ secrets.GREENLIGHTBOT_PAT }}
